#!/usr/bin/env php
<?php

use App\Console\Command\CacheClearCommand;
use Framework\Console\Input;

require __DIR__.'/vendor/autoload.php';

/**
 * @var Psr\Container\ContainerInterface $container
 */
$container = \Framework\Core::InitializeContainer();

$command = $container->get(CacheClearCommand::class);

$input = new Input($argv);

$command->execute($input);