#!/usr/bin/env php
<?php

use App\Console\Command\CacheClearCommand;
use Framework\Console\Application;
use Framework\Console\Input;
use Framework\Console\Output;
use Framework\Core;

require __DIR__.'/vendor/autoload.php';
$container = Core::InitializeContainer();
Core::SetConfiguration($container);

$cli = new Application();

$commands = config('console.commands');
foreach ($commands as $command) {
    $cli->add($container->get($command));
}

$cli->run(new Input($argv), new Output());
